### PR TITLE
Reflect new url immediately when transition cache is used.

### PR DESCRIPTION
**Pull request by smidwap**
The fix (6be3c4a5c8010705e953905a4f0a46b10426dd0d) to issue #353 had a negative side effect on transition cache. By waiting to change the url until the ajax response for the new page is received, a user will see the cached copy while the location bar still reflects the last page's url.

The two consequences to this are:

1. Weird url-changing behavior for the user
2. Any javascript that relies on `document.location` on `page:change` will break. Our app has javascript to create links to navigate back in the app. This javascript became buggy as a result.

Here's a breakdown of how to reproduce:

1. Enable transition cache: `Turbolinks.enableTransitionCache()`
2. Go to Page A and click link to Page B
3. Click a link to go to Page A (which will show a cached copy before loading the fresh page)
4. You'll notice Page B's url is still shown while waiting for Page A's fresh copy to load.

In this PR, I chose to get rid of the `rememberReferer` function. It didn't seem to a serve a purpose with this fix in place. But I could be missing something, so happy to bing it back if needed.

### CODE REVIEW

**Comment by elia** [comment]
I'd like to see this merged too

**Comment by smidwap** [comment]
Just reminded about this, @elia.

Are there any hesitations? Happy to resolve merge conflicts once I know everyone's onboard. I'm using a fork of Turbolinks in production to apply the fix, so it'd be great to get this merged!

**Comment by smidwap** [comment]
Thanks Thibaut!

**Comment by Thibaut** [comment]
No problem :+1: 
Sorry it took this long.

**Pull request closed without merging**
