### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by Thibaut**

### CODE REVIEW

**Comment by reed** [comment]
Wait, why are we executing scripts on `fetchHistory` now?

**Comment by Thibaut** [comment]
@reed This code/behavior hasn't changed in at least 6 months. I just noticed the unnecessary variable.

**Comment by reed** [comment]
Actually, it changed 8 days ago in this commit: 7c9d6b279b9d21c2d81b75bc32b43193bb070196.  Moving `extractTitleAndBody` into `changePage` resulted in `runScripts` being set regardless of whether it was `fetchReplacement` or `fetchHistory` that called `changePage`.

**Comment by Thibaut** [comment]
@reed You're right. Sorry I looked at the wrong code. Why should we not execute scripts on `fetchHistory`?

**Comment by reed** [comment]
Because those scripts have already been executed for that page.  And since the transition cache uses `fetchHistory`, the scripts would run then too.

**Comment by Thibaut** [comment]
Makes sense. The lack of tests had to bite us on that big PR :P
I'll fix this soon.

**Comment by reed** [comment]
Yeah, without tests it's easy to miss important things like this when they're implemented so subtly.

**Pull request closed without merging**
