### PR TITLE
Add ability to re-run scripts on back/forward navigation

### LINKED ISSUE #507: Turbolinks doesn't run scripts on `back`
Looks like Turbolinks doesn't re-run scripts in the body when the back button is pressed:
https://github.com/rails/turbolinks/blob/master/lib/assets/javascripts/turbolinks.js.coffee#L94 - is there a specific reason for this? Could we change this or make it configurable?

@Thibaut

### PR DESCRIPTION
**Pull request by Thibaut**
… by specifying `data-turbolinks-eval=true` on the `<script>` tag.

Fix #507.

cc @reed @kevinhughes27

### CODE REVIEW

**Comment by kevinhughes27** [comment]
:+1:

**Comment by reed** [comment]
I'm on board with the functionality, but I'm not sure about the name of the attribute.  Seems strange that `data-turbolinks-eval=true` and `data-turbolinks-eval=false` don't mean opposite things.  Plus, I think it's always been implied that any script tag without a `data-turbolinks-eval=false` attribute meant that `data-turbolinks-eval=true`.  

Off the top of my head, some alternative names could be `data-turbolinks-cache-eval`, `data-turbolinks-history-eval`, `data-turbolinks-re-eval`, or `data-turbolinks-always-eval`.  Or any other name you think might be better.

**Comment by Thibaut** [comment]
How about `data-turbolinks-eval=always`?

**Comment by reed** [comment]
That would work.

**Comment by Thibaut** [comment]
Updated :+1:

**Comment by reed** [comment]
Thanks

**Comment by Thibaut** [comment]
@reed good catch on the name. `data-turbolinks-eval=false` was confusing.

**Comment by kevinhughes27** [comment]
I like it! thanks guys!

**Comment by gregblass** [comment]
Any idea how I could add this to code in application.js where there is no <script> tag?

**Comment by Thibaut** [comment]
@gregblass bind a function to the `page:load` event. It'll get called every time the page changes (including on back/forward navigation).

**Pull request merged**
