### PR TITLE
Partial replacement docs

### PR DESCRIPTION
**Pull request by Thibaut**
/cc @kristianpd @dhh @reed

### CODE REVIEW

**Comment by reed** [comment]
Looks great.  I wonder if it'd be beneficial to point out in the readme that the partial replacement feature is new to v3.0, especially since it hasn't been released yet.

**Comment by kristianpd** [comment]
:sheep: :it:

**Comment by Thibaut** [comment]
Added one commit: 7a9b63ade9b2cdf8980e06206e87f5bad419e40d

**Comment by phoet** [comment]
@thibaut <3

**Pull request merged**
